"""empty message

Revision ID: 72cfab00dda2
Revises: e7565dbc0305
Create Date: 2019-09-22 21:23:49.193798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72cfab00dda2'
down_revision = 'e7565dbc0305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_address', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('venue_address', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('venue_address', sa.Column('state', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'city')
    op.drop_column('venues', 'state')
    op.drop_column('venues', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue_address', 'state')
    op.drop_column('venue_address', 'phone')
    op.drop_column('venue_address', 'city')
    # ### end Alembic commands ###
