"""empty message

Revision ID: 83d512e46d5a
Revises: a7161732e157
Create Date: 2019-09-21 19:51:09.127102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d512e46d5a'
down_revision = 'a7161732e157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('deslikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'deslikes')
    # ### end Alembic commands ###
