"""empty message

Revision ID: a7161732e157
Revises: b14580acf467
Create Date: 2019-09-21 19:39:22.145412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7161732e157'
down_revision = 'b14580acf467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('link_likes_fkey', 'link', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('link_likes_fkey', 'link', 'genres', ['likes'], ['id'])
    # ### end Alembic commands ###
