"""empty message

Revision ID: b14580acf467
Revises: 47fd817d7701
Create Date: 2019-09-21 19:37:06.783839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14580acf467'
down_revision = '47fd817d7701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_genres',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='artist_genres_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='artist_genres_genre_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id', name='artist_genres_pkey')
    )
    # ### end Alembic commands ###
